CREATE TABLE `empleados` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(45) NOT NULL,
  `CORREO` varchar(80) NOT NULL,
  `CUIL` varchar(15) NOT NULL,
  `FECHA_INGRESO` date NOT NULL,
  `HS_TRABAJADAS` int(11) NOT NULL,
  `SUELDO_BASICO` decimal(10,0) NOT NULL,
  `COMISIONES` decimal(10,0) NOT NULL,
  `HS_MINIMAS` int(11) NOT NULL,
  `COSTO_HORA` decimal(10,0) NOT NULL,
  `TIPO_EMPLEADO` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4